### ISSUE TITLE
high ops/prog/epoch

### ISSUE THREAD

**Issue by ker2x** [paradigms-of-intelligence/cubff#4]
Hello,

did you observe a trend to have high (2000+) ops/prog/epoch combined with low byte/prog after self replication has been achieved ? is it a common trend ?

There isn't much in your paper about your observation after self-replicator domination. is it because nothing much happens ?
your paper also show a surprisingly low number of epochs before finding a self replicator. How many programs did you usually run in 2D worlds ?

Thank you.

**Comment by veluca93** [comment]
Sorry for the delay!

Yes, it is very common for self-replicators to have a much higher density of operations / low bytes/prog.

We haven't investigated much what happens after self-replicator emergence either... or at least, not yet.

In 2d worlds, at least in the ones for the videos, we run about 32k programs.
